# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/breaking-bad
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=admin

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Application Configuration
server.port=8080

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.dev.marshallBits.breakingBadApi=DEBUG

#Password de JWT
jwt.secret=un_password_super_complejo
jwt.expiration=86400000
